### ISSUE TITLE
Deposit Failed - exceeded maximum number of instructions allowed (200000) at instruction #59326

### ISSUE THREAD

**Issue by 0xAltan** [Jungle-Finance/dapp-suppot#1]
**Describe the bug**
Attempted to deposit 1000, and then 5000 fakeRay tokens to the devnet-2 contract, received 'Error' results both times. 

**To Reproduce**
1. Go to 'Deposit'
2. Click on 'Max' in the 'Ray to deposit' box
3. Click on 'devnet-2' on contract
4. Click on 'deposit'
5. Click on 'Approve transaction'
6. See error

**Expected behavior**
Expect success deposit. 

**Screenshots**

Txid screenshot. Txid: 5JYFQjTzw4fFWx5xY8fLz8xNQ79w7xg2WCghRuovLxzt247bFTaMbZhGkjCnMDKZ3cKwQTuV7T9gEvRK6qpqfStY

<img width="1139" alt="Screenshot 2022-08-04 at 23 58 19" src="https://user-images.githubusercontent.com/108236390/182969138-4eb886ed-daa3-407c-a6f3-8bff61a1de38.png">

Error details from transaction simulation. 

<img width="1222" alt="Screenshot 2022-08-04 at 23 59 27" src="https://user-images.githubusercontent.com/108236390/182969275-61ca69e0-27c1-42d2-950a-09287c39c019.png">

**Desktop (please complete the following information):**
 - OS: [Mac OS 12]
 - Browser [chrome]
 - Version [103.0.5060.134]

**Additional context**
Transaction signature: 5JYFQjTzw4fFWx5xY8fLz8xNQ79w7xg2WCghRuovLxzt247bFTaMbZhGkjCnMDKZ3cKwQTuV7T9gEvRK6qpqfStY

**Comment by Chasewhip8** [comment]
> Program returned error: exceeded maximum number of instructions allowed (200000) at instruction #59326

**Comment by ddeanto** [comment]
I believe this is resolved for now as I was able to chip away ~25% of the compute costs.
