### ISSUE TITLE
UI shows success transaction while it is actually failed

### ISSUE THREAD

**Issue by jmarrr** [Jungle-Finance/dapp-suppot#2]
**Describe the bug**
When a transaction is failed the UI pop up notification shows that the transaction succeed.

**To Reproduce**
1. Go to Deposit
2. Click on FakeRay-DevNet-3 / FakeRay-DevNet-2
3. Set the input
4. Approve transaction

**Expected behavior**
Should expect a failed transaction notification if the transaction has error.

**Screenshots**
![a1](https://user-images.githubusercontent.com/26637741/182999843-df6bc817-ada7-4da9-8282-22f8682451fd.png)
![a2](https://user-images.githubusercontent.com/26637741/182999859-ea738e07-1438-4423-843c-d330e069c93a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by Chasewhip8** [comment]
Not a bug this is on purpose so we can get the explorer log for debug purposes on every transaction. Will revert to expected behavior later.
