### ISSUE TITLE
Request to add a pending/loading notification while waiting for a transaction confirmation.

### ISSUE THREAD

**Issue by jmarrr** [Jungle-Finance/dapp-suppot#3]
**Is your feature request related to a problem? Please describe.**
When you approve a transaction the app just shows nothing while waiting for a pending transaction to be completed, it is better to have indicator for users that their transaction is currently pending otherwise panic.

**Describe the solution you'd like**
A pending transaction notification

**Comment by doozenwhale** [comment]
We're working on it!

**Comment by Chasewhip8** [comment]
Added transaction queue still WIP but does this
