### ISSUE TITLE
Better feedback for Withdraw I-token failed - Error: WithdrawAmountTooSmall

### ISSUE THREAD

**Issue by 0xAltan** [Jungle-Finance/dapp-suppot#4]
**Describe the bug**
Cannot withdraw I-token or J-token separately from the devnet-2 contract.

**To Reproduce**
1. Go to 'withdraw'
2. Click on '...' icon on the right side of the withdraw page title. 
3. Scroll down to 'Withdraw I'
4. Select 100 J-Ray to withdraw
5. Click on 'withdraw' below
6. Approve transaction on wallet
7. See error

**Expected behavior**
Approved transaction. 

**Screenshots**

Signature: 2Wb16VmyUQhuSfQSg296FjwFBAcHkSdidUhnGTQe3Kjs5CetQ15Xh768TT4nMBPBkXQ3VrLTC8ektDkvru7YUaE6

<img width="1163" alt="Screenshot 2022-08-05 at 10 07 26" src="https://user-images.githubusercontent.com/108236390/183043771-448ace6e-7390-4929-9942-d7b134b83453.png">

**Desktop (please complete the following information):**
 - OS: [Mac OS 12]
 - Browser [Chrome]
 - Version [103.0.5060.134]

**Comment by doozenwhale** [comment]
This is expected behavior, we could use more user feedback to mitigate confusion

**Comment by doozenwhale** [comment]
@Chasewhip8 DM me about this one

**Comment by Chasewhip8** [comment]
Fixed in latest public beta
