### ISSUE TITLE
Multiple zeros before a natural number when inputing deposit or withdraw amount

### ISSUE THREAD

**Issue by arctictea** [Jungle-Finance/dapp-suppot#5]
**Is your feature request related to a problem? Please describe.**
When one inputs the number of tokens one wishes to deposit there is always a zero in front. It seems you can't get rid of it unless you first press the "max" button and then delete the max amount from the input field. Futhermore, you can add multiple zeros before you input a natural number. So you could input 0000000100 and it will read as 100. Although this is still correct,it may feel very off putting and that it wasn't designed well as most users are used to no zeros in front when using defi apps (or most things for that matter.

Natural numbers are that they do not include zero or negative numbers. Was the best way to describe it.

![0](https://user-images.githubusercontent.com/108090333/183111920-36579f3a-9281-45ca-b6df-d157a7e5f2a4.PNG)

**Describe the solution you'd like**
No zeros in front of natural numbers.

**Comment by Chasewhip8** [comment]
This is a weirdly complex issue that I have been trying to fix for a bit haha. Working on it.
