### ISSUE TITLE
Withdraw RAY amount of I+J does not equal individual I RAY withdraw and J  RAY withdraw amounts added together

### ISSUE THREAD

**Issue by arctictea** [Jungle-Finance/dapp-suppot#6]
**Describe the bug**
When adding together the amount of Ray tokens you receive from withdrawing individually the I-tokens and J-tokens it does not add up to the same amount as when you withdraw I+J together. It is less.

**To Reproduce**
1. Deposit Ray to get I-tokens and J-tokens. I used 100 Ray in this example.
3. Go to the withdraw tab located on the left-hand side of the screen.
4. Go to the Withdraw IJ dropdown selection and press max amount for all. Take note of the amount of the amount of Ray you will receive. 
![IJ](https://user-images.githubusercontent.com/108090333/183115665-131cd489-4ddb-4195-9886-249ed580f85c.PNG)

5. Now go to the Withdraw I dropdown selection and press max. Take note of the amount of the amount of Ray you will receive. 
![I](https://user-images.githubusercontent.com/108090333/183115707-83b089a8-caa9-420e-94bb-9518d8063066.PNG)

6. Now go to the Withdraw J dropdown selection and press max. Take note of the amount of the amount of Ray you will receive.
![J](https://user-images.githubusercontent.com/108090333/183115740-cee9d0bc-e652-4545-b080-cec622000e00.PNG)

7. Add the Withdraw I and Withdraw J amounts together. It will be lesser than the Withdraw IJ amount.

**Expected behavior**
Individual withdraw of I and J dropdowns equal the Withdraw IJ dropdown amounts.

**Screenshots**
Above in each step.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 104.0.5112.81 (Official Build)

**Comment by doozenwhale** [comment]
Thank you! Since vault2 has not expired yet, there is nothing in the corresponding i-redeem-pool to "withdraw" from. Our gui is showing you get 0 in return in "WITHDRAW I", but in fact, the gui probably shouldn't even let you choose this option while the i-redeem-pool is empty. Regardless, I believe this is expected behavior. NOTE: the fakeRay in the j-redeem-pool (where WITHDRAW J "withdraws" from), is from vault1's expiry.

**Comment by arctictea** [comment]
No problem! Good to know it is expected behavior.
