### ISSUE TITLE
Confusing display of fees when withdrawing

### ISSUE THREAD

**Issue by arctictea** [Jungle-Finance/dapp-suppot#7]
**Is your feature request related to a problem? Please describe.**
The way that the "0.2% fee • xxx.xx RAY is taken to support the Jungle platform" fee description is displayed is confusing. It appears as if there are two fees. It appears as if one fee is the 0.2%, and another fee is the xxx.xx Ray amount taken to support the Jungle platform.

Another issue is that the "•" symbol could also be interpreted as a multiplication symbol.

![IJ](https://user-images.githubusercontent.com/108090333/183117147-13d6800f-bdfa-4ab9-8313-384a0b819d12.PNG)

**Describe the solution you'd like**
Since it is one fee, take away the "•" symbol and instead use brackets as an explainer. For example, "0.2% fee (xxx.xx RAY) is taken to support the Jungle platform)"

**Describe alternatives you've considered**
Put brackets or maybe even include a link to the docs on the fees for more detail if they wish.

**Comment by Chasewhip8** [comment]
Would replacing the dot with "or" be more intuitive?
> 0.2% fee, or 0.199999999 Ray, is taken to support the jungle platform

**Comment by doozenwhale** [comment]
Would replaying the dot with "=" be even more intuitive?

> 0.2% fee = 0.199999999 Ray, is taken to support the jungle platform

**Comment by arctictea** [comment]
> Would replaying the dot with "=" be even more intuitive?
> 
> > 0.2% fee = 0.199999999 Ray, is taken to support the jungle platform

Yes this would be the clearer display solution of the two options. 

The "or" display may seem like I have a choice of either choosing the 0.2% fee or an xxx.xx amount of Ray to pay (even though it is the same). Yes I know this way of thinking may seem very silly haha but we gotta think of all possible situations and make it as simple and clear as possible.

Conclusion: Yes, the "=" sign is the most clear way to display the fees of the two options.

**Comment by arctictea** [comment]
Or you could just have the 0.2% display only. 

"0.2% fee is taken to support the Jungle platform". 

The user should understand this is why they have a lesser amount when withdrawing because of this 0.2% fee.

I personally like this one haha but I understand that some people may be very lazy to calculate.

**Comment by doozenwhale** [comment]
the `=` sign looked best to me.

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/110686538/184471314-1159949d-57b1-42a7-b74a-cef6feafc821.png">

**Comment by Chasewhip8** [comment]
Went with =
